version: 2

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/norml
    binary: norml
    ldflags:
      - -s -w -X main.AppVersionMetadata={{ .CommitTimestamp }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}
    format_overrides:
      - goos: windows
        formats:
          - zip
